var json_Commercesdeservices_3 = {
"type": "FeatureCollection",
"name": "Commercesdeservices_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "CREDIT MUTUEL", "quoi": null, "catégorie": "Commerces de services", "obs": "Pour joindre votre Caisse le 05 62 28 71 58 ou 02366 et sur creditmutuel.fr \/ Pour le Service Bancassurance en ligne (lundi-Samedi de 8h à 20h) au 09 69 39 19 91 \/ Pour les oppositions au 03 88 40 10 00 \/ Pour les déclarations de sinistres Automobile au", "adresse": "Place du Souvenir", "numéro": "05 62 28 71 58", "mail": "02366@ creditmutuel.fr", "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.375991653908245, 43.956615069319277 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "AXA CAPELLE", "quoi": "Assurances", "catégorie": "Commerces de services", "obs": null, "adresse": "1, Place du Lion d'Or", "numéro": "05 62 28 12 27", "mail": "agence.capellecondom@axa.fr", "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.371561, 43.957488 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "JEUX M'INFORM", "quoi": "Impression", "catégorie": "Commerces de services", "obs": "Ouvert du mardi au vendredi, de 14h à 18h, 1 pers. à la fois - envoyer par mail les documents à imprimer \/ Réparation de matériel prioritaire (télétravail, médical, étudiant). Impression 3D (base de masque lavable)", "adresse": "33, Bd St Jacques", "numéro": "05 62 68 39 92", "mail": "jeuxminform@free.fr", "Site": "https:\/\/jeuxminform.jimdofree.com\/\n" }, "geometry": { "type": "Point", "coordinates": [ 0.365604, 43.9569 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "FEUILLE A FEUILLES", "quoi": "Graphisme, imprimerie, informatique", "catégorie": "Commerces de services", "obs": "Dépôt chez un commerçant partenaire. Délais de traitement des commandes entre 7 et 15 jours.", "adresse": "46, Rue Gambetta", "numéro": null, "mail": "feuilleafeuilles@free.fr", "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.375418, 43.957075 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "ETS LABORDE", "quoi": "Télé electroménager", "catégorie": "Commerces de services", "obs": "Joignable par téléphone ou mail, du mardi au samedi, de 10h à 12h, uniquement pour les dépannages", "adresse": "24, Rue Honoté Cazaubon", "numéro": "05 62 28 05 50", "mail": null, "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.370953, 43.956185 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "PROXI CONFORT", "quoi": "Télé electroménager", "catégorie": "Commerces de services", "obs": "Joignable par téléphone du mardi au vendredi, de 9h à 12h, uniquement pour les dépannages.", "adresse": "Chemin de Bellefille", "numéro": "05 62 68 23 98", "mail": null, "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.355327284204991, 43.946048716881414 ] } },
{ "type": "Feature", "properties": { "code posta": "32100", "commune": "CONDOM", "qui": "AXA DELPECH", "quoi": "Assurances", "catégorie": "Commerces de services", "obs": "Joignable par téléphone et par mail, du lundi au vendredi, de 8h30 à 12h30 et de 14h à 18h", "adresse": "4, Quai Jaubert", "numéro": "05 62 28 00 61", "mail": "agence.delpech@axa.fr", "Site": null }, "geometry": { "type": "Point", "coordinates": [ 0.369292, 43.958266 ] } }
]
}
